services:
  - type: web
    name: effatha-gene-highlighter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: NCBI_TOOL_EMAIL
        sync: false  # defina no painel do Render como Secret
